### PR TITLE
fix goreleaser docker multiarch

### PR DESCRIPTION
**Pull request by joconcepts**

### CODE REVIEW

**Comment by lukasmalkmus** [comment]
@joconcepts Sorry that I'm only following up on this now. I'll happily merge this but just a handful questions:

1. Can you update the README.md and adjust the `docker` commands to use one of the new image tags. Otherwise people following the README might run into errors/blockers as `latest` won't resolve anymore.
2. Have you tested this locally or do I need to do some testing?

**Comment by joconcepts** [comment]
@lukasmalkmus latest still exists but it resolves to the correct architecture image. You need to test that if possible but I'm quiet sure that it works.

**Comment by lukasmalkmus** [comment]
@joconcepts Ah nice, didn't know that! Neat! I'll go ahead and merge this but can only test it on monday/tuesday so might take until then to cut a fresh release.

**Review by lukasmalkmus — APPROVED** [review]
LGTM

**Pull request merged**
