### PR TITLE
implement address and geohash labels

### PR DESCRIPTION
**Pull request by carazzim0**
Hi @lukasmalkmus,

I added the following labels:
* geohash
* address
* city
* brand

With the geohash label you can create quite (imho) cool worldmap panels in Grafana
grafana-screenshot-worldmap

With the address / city / brand label you can see more clearly which gas station in the city is displayed
Bildschirmfoto 2020-03-12 um 09 23 08

There are some string manipulations in the code now because sometimes the city names are in full caps, streets are with trailing whitespaces and other really annoying stuff.

Please let me know what you think and if there's something you would want me to improve codewise. Still kinda new to go :)

cheers!

### CODE REVIEW

**Comment by carazzim0** [comment]
Hm I think the build failed due to the missing `go mod vendor`. Rebased and pushed.

**Comment by lukasmalkmus** [comment]
Do you mind sharing the Grafana Map setup? Either put it here or add something to the [README.md]. After this PR lands I want to pin a new minor release.

Do you mind me using your Screenshot in the README for explanation?

**Comment by carazzim0** [comment]
Thanks!

Sure there you go. Note: We let Prometheus add a user label because I have set this up for a colleague of mine as well.

query:
Bildschirmfoto 2020-03-12 um 09 55 51

worldmap settings:
`Center` setting must be adjusted accordingly if you want your map to start showing somewhere else. Also note the `Field Mapping`s
Bildschirmfoto 2020-03-12 um 09 56 15

dashboard variables:
Bildschirmfoto 2020-03-12 um 09 57 02

You may use these screenshots if you like :)

**Comment by lukasmalkmus** [comment]
Thanks dude 🙌

**Comment by lukasmalkmus** [comment]
I just tagged a new release with your changes.

**Comment by carazzim0** [comment]
Awesome! Thank you very much 😄

**Pull request merged**
